envkernel.sh: fix sourcing since pma!1063 merge (!1892)
Change pmaports path `aports/device/device-*` to `aports/device/testing/device-*`
to match the directory structure changes after pmaports!1063 got merged.

Without this change sourcing `envkernel.sh` with up-to-date `pmbootstrap` & `aports` would fail with:

  ERROR: Please select a valid device in 'pmbootstrap init'
  See also: <https://postmarketos.org/troubleshooting>